[package]
name = "miette-tab-error-repro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = { version = "3.0.1", features = ["fancy"] }
thiserror = "1.0.29"
